# Site settings
title: Caychen
description: 只是万万千千程序猿中的一只小菜鸟，喜欢学习编程，喜欢探索新技术！！！
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://caychen.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner Section
hero: 112.jpg
hero-title: Welcome
hero-description: 喜欢学习编程，喜欢探索新技术

# Author - Creator
author-name: Caychen
author-image: 10.jpg
about-author: 我的英文名是Caychen，只是万万千千程序猿中的一只小菜鸟，喜欢学习编程，喜欢探索新技术！！！
author-email: caychen@aliyun.com
formspree-email: https://formspree.io/f/xyyoybnv
author-github: https://www.github.com/caychen
author-gitee: https://www.gitee.com/caychen
author-csdn: https://www.blog.csdn.net/caychen
author-jianshu: https://www.jianshu.com/u/c64d133ef703

# Social Media Links (Links are located in hero and footer)
email: caychen@aliyun.com
github: https://www.github.com/caychen
twitter: https://twitter.com
facebook: https://facebook.com
google-plus: https://plus.google.com/
instagram: https://www.instagram.com/
pinterest: https://pinterest.com/
youtube: https://www.youtube.com/

# Contact Form Settings
contact-subtitle: 如果有任何想法，欢迎给我留言。

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
